openapi: 3.0.0
info:
  title: API Gateway
  version: 1.0.0
  description: API Gateway for managing requests

paths:
  /provaProxy:
    get: 
      summary: Prova proxy
      operationId: provaProxy
      responses:
        '200':
          description: OK
  /reqapi/requests:
    get:
      summary: Get all requests 
      operationId: getAllRequests
      responses:
        '200':
          description: OK
    post: 
      summary: Create a new request
      operationId: createRequest
      responses: 
        '201':
          description: Created
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /reqapi/requests/{id}:
    get:
      summary: Get a request by id
      operationId: getRequestById
      responses: 
        '200':
          description: OK
        '404':
          description: Not found
    put:
      summary: Update a request by id
      operationId: updateRequestById
      responses: 
        '200':
          description: OK
        '404':
          description: Not found
    delete:
      summary: Delete a request by id
      operationId: deleteRequestById
      responses: 
        '200':
          description: OK
        '404':
          description: Not found
        

  
components:
  schemas:
    Request:
      type: object
      properties:
        id:
          type: integer
        # Add other properties for request
