openapi: 3.0.0
info:
  title: API Gateway
  version: 1.0.0
  description: API Gateway for managing requests

paths:
  /ping:
    get: 
      summary: Ping API Gateway
      operationId: ping
      responses:
        '200':
          description: OK
  /pg/requests:
    get:
      summary: Get all requests 
      operationId: getAllRequests
      responses:
        '200':
          description: OK
  #   /requests/requests:
  #     get:
  #       summary: Get all requests 
  #       operationId: getAllRequests
  #       responses:
  #         '200':
  #           description: OK
  /serviceDiscoveryTrial: 
    get:
      summary: A trial
      operationId: discoveryTrial
      responses:
        '200':
          description: OK
  /requests/newRequest:
    post:
      summary: Create a new request
      operationId: createNewRequest
      responses:
        '200':
          description: OK
  /requests/request/{id}:
    get:
      summary: Get a request by id
      operationId: getRequestById
      responses:
        '200':
          description: OK
    put:
      summary: Update a request by id
      operationId: updateRequestById
      responses:
        '200':
          description: OK
    delete:
      summary: Delete a request by id
      operationId: deleteRequestById
      responses:
        '200':
          description: OK
  /reqapi/requests:
    get:
      summary: Get all requests from service discovery commesse api 
      operationId: getRequestsFromCommesseApi
      responses:
        '200':
          description: OK
  /provaProxyy: 
    get: 
      summary: proxy prova
      operationId: provaProxy
      responses:
        '200':
          description: OK


components:
  schemas:
    Request:
      type: object
      properties:
        id:
          type: integer
        # Add other properties for request
